codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "30...70"

coverage:
  status:
    project: # settings affecting project coverage
      default:
        threshold: 5%  # allow for 5% reduction of coverage without failing

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true

ignore:
  - "tests/.*"
  - "_version.py"
  - "setup.py"
  - "examples/*"
  - "docs/"
